# Generated by Django 5.2.7 on 2025-12-15 02:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('descripcion', models.TextField()),
                ('fecha_solicitada', models.DateField()),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('en_proceso', 'En proceso'), ('finalizado', 'Finalizado')], default='solicitado', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
