# Generated by Django 5.2.7 on 2025-12-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0002_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('tela', 'Tela'), ('cuero', 'Cuero'), ('plastico', 'Plástico'), ('metal', 'Metal'), ('otro', 'Otro')], max_length=20)),
                ('cantidad_disponible', models.IntegerField()),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('marca', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
    ]
