# Generated by Django 5.2.7 on 2025-12-15 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0003_insumos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insumos',
            new_name='Insumo',
        ),
    ]
