# Generated by Django 5.2.7 on 2025-12-15 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0004_rename_insumos_insumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='plataforma',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp'), ('PRESENCIAL', 'Presencial'), ('SITIO_WEB', 'Sitio Web'), ('OTRA', 'Otra')], default='WHATSAPP', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='plataforma_otra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('EN_PROCESO', 'En proceso'), ('REALIZADA', 'Realizada'), ('ENTREGADA', 'Entregada'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='SOLICITADO', max_length=20),
        ),
        migrations.CreateModel(
            name='PedidoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='pedidos/')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='appTienda.pedido')),
            ],
        ),
    ]
