# Generated by Django 5.2.7 on 2025-12-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0005_pedido_estado_pago_pedido_plataforma_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['nombre_cliente']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_base',
            field=models.PositiveIntegerField(),
        ),
    ]
