# Generated by Django 5.2.7 on 2025-12-15 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0006_alter_categoria_options_alter_insumo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appTienda.producto'),
        ),
    ]
