# Generated by Django 5.2.7 on 2025-12-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0007_pedido_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario_red_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
