# Generated by Django 5.2.7 on 2025-12-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0008_pedido_telefono_pedido_usuario_red_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_solicitada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
