# Generated by Django 5.2.7 on 2025-12-16 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0009_alter_pedido_fecha_solicitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 9 dígitos.', regex='^\\d{9}$')]),
        ),
    ]
