# Generated by Django 5.2.7 on 2025-12-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0010_alter_pedido_correo_alter_pedido_telefono'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['SOLICITADO', 'APROBADO', 'EN_PROCESO', 'REALIZADA', 'ENTREGADA', 'FINALIZADA', 'CANCELADA'])), name='pedido_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('estado_pago__in', ['PENDIENTE', 'PARCIAL', 'PAGADO'])), name='pedido_estado_pago_valido'),
        ),
    ]
