# Generated by Django 5.2.7 on 2025-12-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0011_pedido_pedido_estado_valido_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedido',
            name='pedido_estado_valido',
        ),
        migrations.RemoveConstraint(
            model_name='pedido',
            name='pedido_estado_pago_valido',
        ),
    ]
